"$schema" = "./kaledis.schema.json"
modules = ["Audio", "Data", "Event", "Font", "Graphics", "Image", "Joystick", "Keyboard", "Math", "Mouse", "Sound", "System", "Thread", "Timer", "Window"]
exclude_modules = []

[project]
name = "psych0"
love_path = 'C:\Program Files\LOVE'
version = "11.5"
console = true
accelerometer_joystick = true
external_storage = false
gamma_correct = false
src_path = "src"
asset_path = "assets"

[window]
title = "Untitled"
width = 800
height = 600
borderless = false
resizable = false
minwidth = 1
minheight = 1
fullscreen = false
fullscreentype = "Desktop"
vsync = 1
msaa = 0
display = 1
highdpi = false
usedpiscale = true

[audio]
mic = false
mix_with_system = true
