syntax = "Luau"
column_width = 120
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "None"
collapse_simple_statement = "Always"
space_after_function_names = "Never"
block_newline_gaps = "Never"

[sort_requires]
enabled = true